load("//third_party/java:rules.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "basic",
    srcs = [
        "Example.java",
        "package-info.java",
    ],
    resources = [
        "Example.gwt.xml",
        "public/index.html",
    ],
    deps = [
        "//core/src/main/java/zemeckis:core",
        "//third_party/java:gwt_user",
        "//third_party/java:jsinterop_annotations",
    ],
)
