load("@j2cl//build_defs:rules.bzl", "j2cl_library")
load("//third_party/java:rules.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "core",
    srcs = [
        "AbstractExecutor.java",
        "AfterFrameExecutor.java",
        "AnimationFrameExecutor.java",
        "Cancelable.java",
        "CircularBuffer.java",
        "DeadlineBasedExecutor.java",
        "GwtIncompatible.java",
        "JsRuntime.java",
        "MacroTaskExecutor.java",
        "MicroTaskExecutor.java",
        "OnIdleExecutor.java",
        "RoundBasedExecutor.java",
        "TaskEntry.java",
        "TemporalScheduler.java",
        "UncaughtErrorHandler.java",
        "UncaughtErrorHandlerSupport.java",
        "VirtualProcessorUnit.java",
        "VirtualProcessorUnitsHolder.java",
        "Zemeckis.java",
        "ZemeckisConfig.java",
        "ZemeckisLogger.java",
        "ZemeckisTestUtil.java",
        "ZemeckisUtil.java",
        "package-info.java",
    ],
    resources = [
        "Zemeckis.gwt.xml",
        "ZemeckisConfig.native.js",
        "ZemeckisDev.gwt.xml",
        "zemeckis.js",
    ],
    deps = [
        "//third_party/java:base",
        "//third_party/java:braincheck_core",
        "//third_party/java:grim_annotations",
        "//third_party/java:grim_processor",
        "//third_party/java:jsinterop_annotations",
        "//third_party/java:org_jetbrains_annotations",
    ],
)

j2cl_library(
    name = "core-j2cl",
    srcs = [
        "AbstractExecutor.java",
        "AfterFrameExecutor.java",
        "AnimationFrameExecutor.java",
        "Cancelable.java",
        "CircularBuffer.java",
        "DeadlineBasedExecutor.java",
        "GwtIncompatible.java",
        "JsRuntime.java",
        "MacroTaskExecutor.java",
        "MicroTaskExecutor.java",
        "OnIdleExecutor.java",
        "RoundBasedExecutor.java",
        "TaskEntry.java",
        "TemporalScheduler.java",
        "UncaughtErrorHandler.java",
        "UncaughtErrorHandlerSupport.java",
        "VirtualProcessorUnit.java",
        "VirtualProcessorUnitsHolder.java",
        "Zemeckis.java",
        "ZemeckisConfig.java",
        "ZemeckisConfig.native.js",
        "ZemeckisLogger.java",
        "ZemeckisTestUtil.java",
        "ZemeckisUtil.java",
        "package-info.java",
        "zemeckis.js",
    ],
    experimental_enable_jspecify_support_do_not_enable_without_jspecify_static_checking_or_you_might_cause_an_outage = True,
    deps = [
        "//third_party/java:braincheck_core-j2cl",
        "//third_party/java:grim_annotations-j2cl",
        "//third_party/java:jsinterop_annotations-j2cl",
        "//third_party/java:jspecify-j2cl",
        "//third_party/java:org_jetbrains_annotations-j2cl",
        "@jsinterop_base//:jsinterop-base-j2cl",
    ],
)
